# โ ุชุนุฑูู ุงูุฎุฏูุงุช ุงููุทููุจุฉ ุนูู ููุตุฉ Render
services:
  - name: wp-ai-agent             # ๐ท๏ธ ุงุณู ุงูุฎุฏูุฉ (ููุณุชุฎุฏู ูู ููุญุฉ ุงูุชุญูู)
    type: web                     # ๐ ููุน ุงูุฎุฏูุฉ: ุชุทุจูู ููุจ (ูููู ุงููุตูู ูู ูู ุงูุฅูุชุฑูุช)
    env: python                   # ๐ ุจูุฆุฉ ุงูุชุดุบูู: Python
    plan: free                    # ๐ธ ุงูุฎุทุฉ: ูุฌุงููุฉ
    region: oregon               # ๐ ูููุน ุงูุฎุงุฏู (ูุงุจู ููุชุบููุฑ ุญุณุจ ุงูุฃูุฑุจ ุฌุบุฑุงูููุง)

    # โ๏ธ ุฃูุฑ ุงูุจูุงุก ูุชุซุจูุช ุงูุงุนุชูุงุฏุงุช ูู requirements.txt
    buildCommand: pip install -r requirements.txt

    # โถ๏ธ ุงูุฃูุฑ ุงูุฐู ููุดุบูู ุงูุชุทุจูู (FastAPI ุนุจุฑ Uvicorn)
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT

    # โ ุชุนุฑูู ูุชุบูุฑุงุช ุงูุจูุฆุฉ
    envVars:
      - key: REDIS_URL
        value: redis://red-xxxxxxx:6379  # ๐ฅ ููุงุญุธุฉ: ูุฌุจ ุชุนุฏูู ูุฐุง ุฅูู ุนููุงู Redis ุงููุนูู ูู ููุญุฉ Render
      - key: ENV
        value: production                # ๐ข ูุถุน ุงูุชุดุบูู: Production
